config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  resources :users

  resources :contributions do
    collection do
      patch :approve_all
    end
    member do
      patch :approve
    end
  end
end

app/views/layouts/shared/menu/_footer.html.erb
<footer class="pt-3 mt-4 text-muted border-top">
  &copy; 2024
</footer>

app/views/layouts/shared/menu/_navbar.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>"><%= t('dashboard') %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user.admin? %>
          <li class="nav-item">
            <a class="nav-link  <%= 'active' if current_page?(users_path) %>" aria-current="page" href="<%= users_path %>"><%= t('controller.users') %></a>
          </li>
        <% end %>

        <% if current_user.admin? %>
          <li class="nav-item">
            <a class="nav-link  <%= 'active' if current_page?(contributions_path) %>" aria-current="page" href="<%= contributions_path %>"><%= t('controller.contributions') %></a>
          </li>
        <% end %>
      </ul>
      <div class="d-flex">
        <div class="dropdown">
          <a class="nav-link dropdown-toggle" style="color: #ffffff;" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= edit_user_path(current_user)%>"><i class="fa-solid fa-user-edit"></i> <%= t('edit') %></a></li>
            <li>
              <%= link_to destroy_user_session_path, class:"dropdown-item", data: { turbo_method: :delete } do %>
                <i class="fa-solid fa-sign-out"></i> <%= t('sign_out') %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>
<% end %>