config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  resources :users

  resources :contributions do
    collection do
      patch :approve_all
    end
    member do
      patch :approve
    end
  end
end

app/models/contribution.rb
# == Schema Information
#
# Table name: contributions
#
#  id           :bigint           not null, primary key
#  status       :boolean          default(FALSE)
#  value        :decimal(, )      default(0.0)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  portfolio_id :bigint           not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_contributions_on_portfolio_id  (portfolio_id)
#  index_contributions_on_user_id       (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (portfolio_id => portfolios.id)
#  fk_rails_...  (user_id => users.id)
#
class Contribution < ApplicationRecord
  acts_as_hashids

  belongs_to :portfolio
  belongs_to :user

  validates :value, presence: true, numericality: { greater_than: 0 }
  validates :value, numericality: { less_than_or_equal_to: 1_000_000_000 }

  def update_portfolio_applied_value
    if Contribution.count >= 1
      Portfolio.update(applied_value: Contribution.sum(:value))
    else
      Portfolio.update(applied_value: value)
    end
  end
end

app/controllers/contributions_controller.rb
# The ContributionsController is responsible for handling the creation of new contributions and displaying all conttr
class ContributionsController < ApplicationController
  def index
    @contributions = Contribution.all
    authorize @contributions
  end

  def new
    @contribution = Contribution.new

    authorize @contribution
  end

  def approve
    @contribution = Contribution.find(params[:id])
    authorize @contribution
    @contribution.update(status: true)
    @contribution.update_portfolio_applied_value
    @contribution.user.update(participation: @contribution.user.user_participation)
    redirect_to contributions_path
  end

  def approve_all
    return unless current_user.admin?

    Contribution.all.each do |contribution|
      contribution.update(status: true)
      contribution.user.update(participation: contribution.user.user_participation)
    end
    redirect_to contributions_path
  end

  def create
    @contribution = current_user.contributions.build(contribution_params)
    @contribution.portfolio_id = current_user.portfolio_id
    authorize @contribution

    if @contribution.save
      handle_successful_save
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def handle_successful_save
    if @contribution.status
      @contribution.update_portfolio_applied_value
      redirect_to contributions_path
    else
      flash[:notice] = t('contribution.successfully_created')
      flash[:alert] = t('contribution.waiting_approval')
      redirect_to root_path
    end
  end

  def contribution_params
    params.require(:contribution).permit(:value, :user_id, :portfolio_id, :status)
  end
end

app/helpers/contributions_helper.rb
# Helper for contributions controller
module ContributionsHelper
end

app/views/contributions/_contribution.html.erb
<div class="modal fade" id="<%= contribution.to_param %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= contribution.to_param %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1"><%= t('contribution.attributes.value') %></span>
          <input type="text" class="form-control" disabled value="<%= number_to_currency(contribution.value) %>" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1"><%= t('contribution.attributes.date') %></span>
          <input type="text" class="form-control" disabled value="<%= contribution.created_at.strftime('%d/%m/%Y') %>" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1"><%= t('contribution.attributes.portfolio') %></span>
          <input type="text" class="form-control" disabled value="<%= contribution.portfolio.name %>" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1"><%= t('contribution.attributes.user') %></span>
          <input type="text" class="form-control" disabled value="<%= contribution.user.name %>" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1"><%= t('contribution.attributes.status') %></span>
          <input type="text" class="form-control" disabled value="<%= contribution.status %>" aria-describedby="basic-addon1">
          <% unless contribution.status %>
            <%= button_to approve_contribution_path(contribution), class: "btn btn-success", method: :patch do %>
              <i class="fa-solid fa-check"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contributions/_create_contribution_alert.html.erb
<div class="modal fade" id="create_contribution_alert" tabindex="-1" aria-labelledby="create_contribution_alert" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t('contribution.new_alert')%></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "contributions/form", contribution: @contribution %>
      </div>
    </div>
  </div>
</div>

app/views/contributions/_form.html.erb
<%= form_with(model: contribution, local: true) do |form| %>
  <div class="mb-3">
    <%= form.label t('contribution.attributes.value'), class: "form-label" %>
    <%= form.number_field :value, class: "form-control" %>
    <%= form_model_errors(@contribution, :value) %>
  </div>

  <% if current_user.admin? %>
    <div class="form-check form-switch">
      <%= form.check_box :status, { class: "form-check-input", id: "contribution_status" }, true, false %>
      <%= form.label :alredy_approved?, t('contribution.attributes.alredy_approved?'), class: "form-check-label", for: "contribution_status" %>
    </div>
  <% end %>

  
  <br>
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <%= form.submit t('submit'), class: "btn btn-sm btn-primary shadow-sm" %>
  </div>
<% end %>

app/views/contributions/index.html.erb
<h1 class="text-center"><%= back_button root_path, "left" %> <%= t('controller.contributions') %></h1>
<br>
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
  <%= link_to t('contribution.approve_all'), approve_all_contributions_path, class: 'btn btn-sm btn-success shadow-sm', data: { turbo_method: :patch } %>
  <%= link_to t('contribution.new'), new_contribution_path, class: 'btn btn-sm btn-primary shadow-sm'%>
</div>
<br>


<ol class="list-group list-group-numbered">
  <% @contributions.each do |contribution| %>
    <li class="list-group-item d-flex justify-content-between align-items-start" data-bs-toggle="modal" data-bs-target="#<%= contribution.to_param %>" data-bs-whatever="@mdo" style="cursor: pointer;">
      <div class="ms-2 me-auto">
        <div class="fw-bold"><%= contribution.user.name %></div>
          <%= number_to_currency(contribution.value) %>
          <%= render "contribution", contribution: contribution %>
      </div>
      
      <% if contribution.status %>
        <span class="badge bg-success rounded-pill"><i class="fa-solid fa-check"></i></span>
      <% else %>
        <span class="badge bg-danger rounded-pill"><i class="fa-solid fa-triangle-exclamation"></i></span>
      <% end %>
    </li>
  <% end %>
</ol>

app/views/contributions/new.html.erb
<h1 class="text-center"><%= back_button contributions_path, "left" %> <%= t('contribution.new') %></h1>
<br>
<%= render "contributions/form", contribution: @contribution %>